<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./style/style.css">
</head>

<body>

<div class="container mt-3">
    <h2>Registracija į Kursus</h2>
    <hr>
    <form method="POST" id="registration">
        <div class="first-name-container">
            <label class="first-name" for="fname">Vardas:</label>
            <input type="text" id="fname" name="first_name" value="John"><br>
        </div>

        <div class="last-name-container">
            <label class="last-name" for="lname">Pavardė:</label>
            <input type="text" id="lname" name="last_name" value="Doe"><br><br>
        </div>

        <label for="cars">Miestas: </label>
        <select id="city" name="city">
            <option value="Kaunas">Kaunas</option>
            <option value="Vilnius">Vilnius</option>
            <option value="Klaipeda">Klaipėda</option>
        </select><br><br>

        <h3>Programavimo kalba:</h3>

        <div class="checkbox-language">
            <input type="checkbox" id="language1" name="lang[]" value="C++">
            <label for="language1"> C++</label><br>
            <input type="checkbox" id="language2" name="lang[]" value="PHP">
            <label for="language2"> PHP</label><br>
            <input type="checkbox" id="language3" name="lang[]" value="Python">
            <label for="language3"> Python</label><br><br>
        </div>

        <h3>Papildoma Informacija</h3>

        <textarea id="w3review" name="additional_information" rows="4" cols="50"
                  placeholder="PVZ. : Turite C++ programacimo patirties "></textarea> <br><br>

        <h3>Select image to upload:</h3>
        <div class="col-4">
            <input type="file" name="image" class="form-control" id="customFile"/>
        </div>

        <br><br>

        <button class="btn btn-secondary" id="submit">Submit</button>

    </form>

    <div class="mt-3">
        <h3>
            <a class="d-none" id="message"></a>
        </h3>
    </div>

    <div class="mt-3">
        <h3 class="d-none" id="messageImgError">

        </h3>
    </div>


</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
<script src="./script/script.js"></script>

</body>

</html>