<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Quiz</title>
</head>

<body>
    <div class="container mt-3 ">
        <div class="d-flex align-items-center justify-content-center vh-100">
            <?php
            echo $tag->setAttr('method', 'POST')->setAttr('id', 'form')->formOpen();
            echo $tag->setTag('h3')->setText($quizJsonDecode[0]['question'])->show();
            foreach ($quizJsonDecode[0]['choices'] as $key => $value) {
                echo $tag->radiosGeneration(htmlspecialchars($value), $key + 1);
            }
            echo $tag->setTag('Button')->setAttr('type', 'submit')->setAttr('class', 'mt-3 btn btn-primary submitButton')->setText('Button')->get();
            echo $tag->formClose();
            ?>
        </div>
    </div>


</body>
</html>

<!-- <?php
        // echo $tag->setAttr('method', 'POST')->formOpen();
        // echo $tag->setTag('h3')->setText($quizJsonDecode[0]['question'])->show();
        // foreach ($quizJsonDecode[0]['choices'] as $key => $value) {
        //     echo $tag->radiosGeneration(htmlspecialchars($value), $key + 1);
        // }
        // echo $tag->setTag('Button')->setAttr('type', 'submit')->setAttr('class', 'mt-3 btn btn-primary submitButton')->setText('Button')->get();
        // echo $tag->setAttr('method', 'POST')->formClose();
        ?> -->