<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<div id="demo">
    <h2 id="text">The XMLHttpRequest Object</h2>
<!--    <button type="button" id="getData">Change Content</button>-->

    <button type="submit" id="getDataButton">Click me</button>
</div>

<script id="data" src="./json/users.json"></script>
<script src="./script/script.js" ></script>
</body>
</html>