<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>

    <div class="container">

        <div class="row mt-5">
            <button class="btn btn-dark col-3" type="submit" id="getDataButton">Click me</button>

            <div class="col">
                <input type="text" id="numberOfUsersToGet" class="form-control" placeholder="add number of users you want to get" aria-label="First name">
            </div>
        </div>

        <div class="mt-3 d-none">
            <a id="downloadLink" href="" download="">Download</a>
        </div>

        <p id="text"></p>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <script id="data" src="./json/users.json"></script>
    <script src="./script/script.js"></script>
</body>

</html>