<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>

    <h2>Registracija į Kursus</h2>

    <hr>

    <form>
        <div class="first-name-container">
            <label class="first-name" for="fname">Vardas:</label>
            <input type="text" id="fname" name="first_name" value="John"><br>
        </div>

        <div class="last-name-container">
            <label class="last-name" for="lname">Pavardė:</label>
            <input type="text" id="lname" name="last_name" value="Doe"><br><br>
        </div>

        <label for="cars">Miestas: </label>
        <select id="city" name="city">
            <option value="kaunas">Kaunas</option>
            <option value="Vilnius">Vilnius</option>
            <option value="Klaipeda">Klaipėda</option>
        </select><br><br>

        <h3>Programavimo kalba:</h3>

        <div class="checkbox-language">
            <input type="checkbox" id="language1" name="clang" value="C++">
            <label for="language1"> C++</label><br>
            <input type="checkbox" id="language2" name="php" value="php">
            <label for="language2"> PHP</label><br>
            <input type="checkbox" id="language3" name="python" value="python">
            <label for="language3"> Python</label><br><br>
        </div>

        <h3>Papildoma Informacija</h3>

        <textarea id="w3review" name="aditinform" rows="4" cols="50"
            placeholder="PVZ. : Turite C++ programacimo patirties "></textarea> <br><br>
        <input type="submit" value="Submit">

    </form>


</body>

</html>